### ISSUE TITLE
Use better resize than nearest

### ISSUE THREAD

**Issue by mrvacbob** [halcy/DeepDanbooruActivationMaps#1]
This line:
`image = np.array(PIL.Image.open(in_path).convert('RGB').resize((299, 299))) / 255.0`

does nearest neighbor resize which makes everything super pixelly. Because of that some of the predictions are really bad, like with: https://danbooru.donmai.us/posts/3068388

If I change it to `PIL.Image.LANCZOS` it gets better.

(Not sure why the model is trained at 299x299 though?)

**Comment by halcy** [comment]
huh, interesting. Does it also improve region estimation?

For why the model is like it is, you'd have to ask kanotype, I didn't train it. Could be they were going for 300^2 and were off by one, who knows >>

edit: oh yeah this improves regions a bunch! what a stupid mistake, thanks, I'd never have noticed.
