### ISSUE TITLE
interpretability？

### ISSUE THREAD

**Issue by koke2c95** [halcy/DeepDanbooruActivationMaps#2]
我玩了一下，有歧义性的tag并不是很能解释激活地图

比如最高确信度的 ganaha hibiki （im@s）99.8%

激活地图很是奇妙....

![1ZIJ91QIE {}_DPLB@}0C2W](https://user-images.githubusercontent.com/26929386/63207297-ea2f4e00-c0f5-11e9-80f2-533d0be26573.png)

嘴巴就很准

是Danbooru的标注不够多？而且有很多歧义性（illustration2vec）准确度不高

**Comment by koke2c95** [comment]
红 衣 服 的 都 是 灵 梦
![IT6B1)N9$1~0DCO}MZJL@CJ](https://user-images.githubusercontent.com/26929386/63207984-801ca600-c101-11e9-8cc5-b3885cb081eb.png)

你以为我面码是白毛？其实我是银发哒！
![O((H8LB)OC4AL~TEW)7IS(2](https://user-images.githubusercontent.com/26929386/63207994-a17d9200-c101-11e9-89fc-ac5462b9872f.png)

**Comment by koke2c95** [comment]
眼睛，嘴巴，头发特征
![DF8SAWQV{ UL{ZKVBZ%P16E](https://user-images.githubusercontent.com/26929386/63208066-90815080-c102-11e9-9207-a2ccfbaab4eb.png)
![YV3LSE7 6ZCC$TPXUR2%EDL](https://user-images.githubusercontent.com/26929386/63208028-28326f00-c102-11e9-836b-bff616b3e718.png)
![FO4%3U4S3@3JP JPQE5 )8H](https://user-images.githubusercontent.com/26929386/63208034-32ed0400-c102-11e9-97f0-ddfa0e944406.png)
![P ~`VNZLC03B$T`3C@T({ N](https://user-images.githubusercontent.com/26929386/63208037-36808b00-c102-11e9-83db-807676f7537a.png)

使用更高层依赖的特征，能更集中（增加了冗余的信息
![DR8WKC%FY)}RLTRIUX7EK9N](https://user-images.githubusercontent.com/26929386/63208051-5adc6780-c102-11e9-939d-f6dc33e34b13.png)


解决歧义性
e-book（确信
![$86Z{(~JQPRL}{97URQA$O4](https://user-images.githubusercontent.com/26929386/63208055-6f206480-c102-11e9-83df-268040c7b99a.png)
 
phone和pad分不清（笑
![32L5J U9IH966`NA8~FS)46](https://user-images.githubusercontent.com/26929386/63208059-81020780-c102-11e9-9f36-185123fcd2b9.png)

**Comment by koke2c95** [comment]
**warning** 

**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**
**NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW NSFW**



dogstyle和sex是一样的激活地图
https://user-images.githubusercontent.com/26929386/63208106-e655f880-c102-11e9-9b0d-03857af98f5d.png

bondage和用跳蛋是一样的激活图
https://user-images.githubusercontent.com/26929386/63208152-4fd60700-c103-11e9-8933-1a42d719b147.png

**Comment by koke2c95** [comment]
结论：
宽纵比压缩跟没压差不多

怀疑估计喂了touhou图在训练集占比很高，不确信的图自动就给出了极高确信度的touhou人物tag
![8HBF3NFY_@`JF_9E1HZ86GY](https://user-images.githubusercontent.com/26929386/63208252-5749e000-c104-11e9-9c52-e494136e58be.png)

总是能找到咱没注意的细节，比如那张JK的sex图给标记出了发带
甚至是pyuko给出了no-humans，in-container的标记
![}Z1QFEXI2YK8OZNQ1QS7SMI](https://user-images.githubusercontent.com/26929386/63208244-40a38900-c104-11e9-97d2-2287c9656387.png)

如果用高级特征去筛选低级特征，感觉可以定位五官什么的
因为用更高的抽象特征能更集中
猜想：高级特征，站立姿势，表情什么的 单独抽出五官腿脚特征无用，但各激活叠加起来能够合成语义，并极其集中和确信

**Comment by halcy** [comment]
not 100% sure what this is about, but I'm glad you're having fun - I will close this issue for now.
